config:
  selfUrl: # https://saas.exchange.dev
  corsOrigins: https://exchange-st-gateway-web,https://exchange-st-gateway-public-web
  connectionStrings:
    administrationService: #
    saasService: #
  authServer:
    authority: # http://exchange-st-authserver
    requireHttpsMetadata: # "false"
    metadataAddress: # https://authserver.exchange.dev/.well-known/openid-configuration
    swaggerClientId: WebGateway_Swagger
  dotnetEnv: Staging
  redisHost: #
  rabbitmqHost: #
  elasticsearchUrl: #
  stringEncryptionDefaultPassPhrase: gsKnGZ041HLL4IM8
  AbpLicenseCode: #

ingress:
  host: saas.exchange.dev
  tlsSecret: exchange-tls

image:
  repository: foryou/exchange-service-saas
  tag: latest
  pullPolicy: IfNotPresent

env: {}      