config:
  selfUrl: # https://web.exchange.dev
  gatewayUrl: # http://exchange-st-gateway-web
  authServer:
    authority: # https://authserver.exchange.dev
    requireHttpsMetadata: # "false"
    isOnK8s: # "true"
    metaAddress: # http://exchange-st-authserver
  dotnetEnv: # 
  redisHost: #
  rabbitmqHost: #
  elasticsearchUrl: #
  stringEncryptionDefaultPassPhrase: gsKnGZ041HLL4IM8
  AbpLicenseCode: #

ingress:
  host: # web.exchange.dev
  tlsSecret: exchange-tls

image:
  repository: foryou/exchange-app-web
  tag: latest
  pullPolicy: IfNotPresent

env: {}