config:
  selfUrl: # https://gateway-web.exchange.dev
  corsOrigins: # https://exchange-st-angular
  globalConfigurationBaseUrl: # http://exchange-st-gateway-web
  authServer:
    authority: # http://exchange-st-authserver
    requireHttpsMetadata: # "false"
    metadataAddress: # https://authserver.exchange.dev/.well-known/openid-configuration
    swaggerClientId: # WebGateway_Swagger
  dotnetEnv: # 
  redisHost: #
  rabbitmqHost: #
  elasticsearchUrl: #
  AbpLicenseCode: #
  
reRoutes:
  accountService:
    url: http://exchange-st-authserver
  saasService:
    url: http://saas-st-administration
  administrationService:
    url: http://exchange-st-administration
  identityService:
    url: http://exchange-st-identity
  productService:
    url: http://exchange-st-product
ingress:
  host: # gateway-web.exchange.dev
  tlsSecret: exchange-tls

image:
  repository: foryou/exchange-gateway-web
  tag: latest
  pullPolicy: IfNotPresent

env: {}